services:

  payload:
    image: node:18.18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
      - nginx
    env_file:
      - .env
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      LETSENCRYPT_HOST: lightson.ai
      LETSENCRYPT_EMAIL: admin@lightson.ai
    volumes:
      - certbot-etc:/etc/letsencrypt  # Persistent storage for certificates (name can be changed)
volumes:
  data:
  node_modules:
  certbot-etc: